### ISSUE TITLE
เพิ่มตัวแปร predicted_arrival_time_extrapolation_BC_duration

### ISSUE THREAD

**Issue by plagad** [traffy-nectec/central#11]
วิธีการหาคือ (ระยะทาง BC / ระยะทาง AB) * เวลา AB หน่วยเป็น Second

**Comment by wichai-t** [comment]
ถ้าระยะทาง AB มีค่าน้อย จะได้ค่า predict ที่สูงมาก
ถ้า ระยะทาง AB == 0, จะได้ค่า predict = infinity
@plagad ช่วย กันให้มันเป็นค่า NULL ให้หน่อยครับ

**Comment by plagad** [comment]
ดัก เป็น Null แล้ว 
- Link Progress ถ้า AC_distance_in_meter_by_linear_ref = 0
- Element การทำนายแบบ Freeflow ทุก Element ถ้าตัวแปร AC_linear_ref_diff = 0
- Element การทำนายแบบ extrapolation ทุก Element ถ้าตัวแปร AC_linear_ref_diff = 0

**หมายเหตุ** Element การทำนาย คือ 
1. predicted_arrival_time_ff_BC_duration
2. predicted_arrival_time_ff_time_str
3. predicted_arrival_time_ff_timestamp
4. predicted_arrival_time_ff_error_in_sec

**Comment by wichai-t** [comment]
> Link Progress ถ้า AC_distance_in_meter_by_linear_ref = 0
> Element การทำนายแบบ Freeflow ทุก Element ถ้าตัวแปร AC_linear_ref_diff = 0
> Element การทำนายแบบ extrapolation ทุก Element ถ้าตัวแปร AC_linear_ref_diff = 0

ไม่ใช่ AB หรอครับ ที่เป็น 0 แล้วต้องดัก 
มี AC เป็น 0 ด้วยหรอครับ ??

**Comment by plagad** [comment]
>> Link Progress ถ้า AC_distance_in_meter_by_linear_ref = 0
>> Element การทำนายแบบ Freeflow ทุก Element ถ้าตัวแปร AC_linear_ref_diff = 0
>> Element การทำนายแบบ extrapolation ทุก Element ถ้าตัวแปร AC_linear_ref_diff = 0

>@plagad  ไม่ใช่ AB หรอครับ ที่เป็น 0 แล้วต้องดัก 
>มี AC เป็น 0 ด้วยหรอครับ ??

@wichai-t เออจริง พิมพ์ใน Github ผิด

**แก้ไข** Element การทำนายแบบ extrapolation ทุก Element ถ้าตัวแปร ~~AC_linear_ref_diff~~ AB_distance_in_meter_by_linear_ref = 0
