### ISSUE TITLE
เพิ่มตัวแปร AC_distance_in_meter และ Link Progress

### ISSUE THREAD

**Issue by plagad** [traffy-nectec/central#12]
AC_distance_in_meter = หาจาก Linear Ref Diff ของ A และ C และระยะทางของ Route ใน Direction นั้น

Link Progress = วิ่งใน link นี้กี่เปอร์เซ็นแล้ว มีค่า -x< x <= 1 
เพราะ AB มีโอกาส < 0 ตอนที่ Check in ก่อนถึงป้าย A ในรัศมี 50 เมตร

**Comment by wichai-t** [comment]
In sim_vehicle_trace_log_v8.csv
---
- [ ] Why AC_distance_in_meter_bylinear_ref always be -1?
- [ ] link_progress has value around [-2442 to 513]
- [ ] BC_distance_in_meter_by_linear_ref has strange value

**Comment by plagad** [comment]
ใส่ชื่อตัวแปร ที่ใช้คำนวณ AC_distance_in_meter_by_linear_ref ผิด ทำให้ได้ค่า -1 ตลอด
เพราะ -1 เป็นค่า Default
![image](https://cloud.githubusercontent.com/assets/604077/19509357/8ca94d8c-9608-11e6-836f-58a5878ccfa4.png)

**Comment by plagad** [comment]
BC_Distance ถ้า Filter เอาฉพาะ ป้ายติดกันจะไม่ผิด
![image](https://cloud.githubusercontent.com/assets/604077/19509899/16c7a7aa-960b-11e6-9a20-2043340dc28c.png)
![image](https://cloud.githubusercontent.com/assets/604077/19509949/5a7f0a10-960b-11e6-8fcb-eca21cd4d322.png)

**Comment by plagad** [comment]
Link Progress น่าจะผิดเพราะ คำนวณ AC_distance_in_meter_by_linear_ref ผิด

**Comment by wichai-t** [comment]
_FYI_
---
There are sometime when link_progress >1:
1. 5554-3565 link ก่อสร้าง เจ้าปัญหา
![image](https://cloud.githubusercontent.com/assets/7189606/19586347/60faec00-977e-11e6-8e5a-1f485cb6a9ca.png)

2. จุดกลับรถดินแดง กระโดดเลย C แต่ยังอยู่ใน 50m = Check-in
![image](https://cloud.githubusercontent.com/assets/7189606/19586424/f3952738-977e-11e6-910d-39cd32ea8d15.png)

3. 1439-1440 และ 1476-147, links ใต้ BTS เจ้าปัญหา ที่ กระโดดเลยป้ายไปเกิน 50m และยังไม่ check-in
![image](https://cloud.githubusercontent.com/assets/7189606/19586454/2683d98c-977f-11e6-84f7-081e3a9ee90a.png)

4. link 5069-338 ที่ถนนบรรทัดทอง link สั้นเกิน (33m) ทำให้เลยป้ายบ่อยๆ
![image](https://cloud.githubusercontent.com/assets/7189606/19586549/355db85a-9780-11e6-883d-4217afdfb93c.png)
