### ISSUE TITLE
AB Distance By Linear Ref มีค่าไม่ปรกติ

### ISSUE THREAD

**Issue by plagad** [traffy-nectec/central#14]
พบว่า ค่า longitude เปลี่ยนแปลงที่ทศนิยมตำแหน่งที่ 6 แต่ Linear Ref เปลี่ยนแปลงเยอะมาก
![image](https://cloud.githubusercontent.com/assets/604077/19511990/07d73400-9614-11e6-98c1-b3499bfa52d8.png)

**Comment by Attapon-K** [comment]
จากที่พี่มูลพบข้อผิดปกติของ linear_ref เลยได้ทำการหาข้อผิดพลาดพบว่า geometry แปลกปลาดตรงบริเวณที่เกิดปัญหา ดังภาพ
![geom](https://cloud.githubusercontent.com/assets/20390063/19512288/5a4311ea-9615-11e6-9046-3d18baf782d6.png)

**Comment by plagad** [comment]
Case 2 
จุดกระโดดไป Check In ที่ป้าย แล้วออกห่างจากป้าย
![image](https://cloud.githubusercontent.com/assets/604077/19512604/e6975042-9616-11e6-8680-52b6ae159c16.png)

**Comment by plagad** [comment]
Case 3
Check In ก่อนป้าย เพราะเส้นทางวนมาหลังป้าย
![image](https://cloud.githubusercontent.com/assets/604077/19512747/94291286-9617-11e6-9595-4b6b99d5a29c.png)

**Comment by wichai-t** [comment]
There are the AC distance which != AB+BC distance:
![image](https://cloud.githubusercontent.com/assets/7189606/19555528/5e8a2054-96e7-11e6-9cc8-9dc189ac286e.png)
where 
- the blue circle mean AB distance < 0. It occurs when bus B is before a stop A.
- red circle data occurs when the GPS is jumping or when the bus is u-turning and still in the same bound, as the figure below.
![image](https://cloud.githubusercontent.com/assets/7189606/19555624/d55c4126-96e7-11e6-96c6-a0001e185cd7.png)

**Comment by Attapon-K** [comment]
geometry แปลกประหลาดตรงบริเวณที่เกิดปัญหา (link id 3621-3622 : 13.76602375,100.6465364) แก้ไขเรียบร้อยแล้วครับ และตำแหน่ง linear_ref ของป้ายรถเมล์ก็แก้ให้เป็นปัจจุบันแล้วครับ
![geom_edited](https://cloud.githubusercontent.com/assets/20390063/19718765/f3e396a0-9b90-11e6-8ec9-e2e7736eeea1.png)

**Comment by Attapon-K** [comment]
@plagad  ปิด Issue ได้เลยครับ
