### ISSUE TITLE
Create new variable: AB_space_mean_speed 

### ISSUE THREAD

**Issue by wichai-t** [traffy-nectec/central#19]
Due to the lack of space mean speed in the current link (AB_space_mean_speed).
And sometimes, the current_space_mean_speed_in_link could not get the right result.
Please consider to make the AB_space_mean_speed by:
```
IF [AB travel time in sec] != 0
THEN ([AB distance in meter by linear ref]/[AB travel time in sec])*3.6
ELSE [Speed]  //simultaneous speed
END
```

Any suggestion is welcome krub :)

**Comment by plagad** [comment]
เริ่มมีตั้งแต่รถ ID 5024130016 ใน ข้อมูล Version 9
