### ISSUE TITLE
Crate link passing id

### ISSUE THREAD

**Issue by wichai-t** [traffy-nectec/central#9]
Generate numbers as 'link passing id' when any bus travel from a stop to any stop.

**Comment by plagad** [comment]
เพิ่มตัวแปร link_passing_id เพื่อบอกว่า GPS ที่วิ่งจาก Stop A ไป Stop C ในรอบนี้ เป็นชุดเดียวกัน

**Comment by wichai-t** [comment]
In sim_vehicle_trace_log_v8.csv
---
Why link_passing_id always be 0?

**Comment by plagad** [comment]
ลืมสั่ง link_passing_id++ ตอน คำนวณ Traveltime เสร็จ 
![image](https://cloud.githubusercontent.com/assets/604077/19509085/2e9421dc-9607-11e6-8584-07c7fe6a22c6.png)
